### ISSUE TITLE
warning : Removed 150 rows containing missing values (geom_point).

### ISSUE THREAD

**Issue by rachel662** [zktuong/ktplots#14]
Hi there, 

I've been trying to plot some cellphonedb results but get this error when trying to use the "chemokines" gene family in the plot_cdbp function
It also just shows numbers rather than the specific ligand-receptor interactions along the y axis?

I also get the same warning but with 18 rows containing missing values when specifying "niche" in the gene family argument
I also get numbers along the y axis in this instance too 

I had to create a new seurat object from the counts and metadata file I used to run cellphoneDB as I had to convert mouse gene names to human ensemble gene names, so extracted the normalised counts file from the seurat object I had (which i merged two separate seurat objects together to make) and worked on that. Am I missing a metadata column perhaps? 

I'd be super grateful for any help with this! 
thanks so much in advance 
Rachel

**Comment by rachel662** [comment]
Hi there, 
sorry to add another issue but I also have an issue with the geneDotPlot function - I get this error
Error in pct/cellNumbers : non-numeric argument to binary operator

again, any help with solving this would be really appreciated 
thanks so much 
Rachel

**Comment by zktuong** [comment]
Hi,  just want to check a few things:

1) can you print the first 6 lines of your seurat meta.data columns that contain the info matching to the  the input meta.txt for cellphonedb? Also print the first 6 lines of your meta.txt here as well.

2) for `geneDotPlot`, what's the full command you're are using for this and what does your object's metadata/size look like.

**Comment by rachel662** [comment]
Hi there

1)

`head(cellphone_seurat@meta.data)
                           orig.ident nCount_RNA nFeature_RNA rownames.merged_object.meta.data.   cell_type
stromal_1_AAACCTGAGAAGGACA    stromal         NA           NA                              <NA>  Cxcl9+ TRC
stromal_1_AAACCTGAGCCCGAAA    stromal   3203.285         3424                              <NA>   Nr4a1+ SC
stromal_1_AAACCTGAGGCATTGG    stromal   2522.613         1806                              <NA>         TRC
stromal_1_AAACCTGAGTTAGGTA    stromal   3039.649         2937                              <NA> Ccl19lo TRC
stromal_1_AAACCTGCATCGACGC    stromal   1893.592          957                              <NA>   Nr4a1+ SC
stromal_1_AAACCTGCATTACGAC    stromal   2742.267         2118                              <NA>         TRC
> `

2)
`head(cellphonedb_meta)
# A tibble: 6 x 2
  `rownames(merged_object@meta.data)` cell_type  
  <chr>                               <chr>      
1 stromal_1_AAACCTGAGAAGGACA          Cxcl9+ TRC 
2 stromal_1_AAACCTGAGCCCGAAA          Nr4a1+ SC  
3 stromal_1_AAACCTGAGGCATTGG          TRC        
4 stromal_1_AAACCTGAGTTAGGTA          Ccl19lo TRC
5 stromal_1_AAACCTGCATCGACGC          Nr4a1+ SC  
6 stromal_1_AAACCTGCATTACGAC          TRC  `

I have noticed that when writing the counts file for cellphonedb, for some reason it wrote the counts file and made my rownames (contatining human ensembl gene names) column 1, as when import the counts file I wrote back into R I can see that the column where the first cell is meant to be contains the ensembl gene names, even though i used row.names=TRUE when writing the counts file? 

this is why the geneDotplot function isn't working i think because it finds 0 genes in the expression matrix 
`data provided is a Seurat object
extracting expression matrix
attempting to subset the expression matrix to the 1 genes provided
found 0 genes in the expression matrix
no groups information provided. defaulting to idents only
preparing the final dataframe ...`

Would cellphoneDB still have run even though the ensembl gene names were column 1 and not the rownames? I didn't get any error message?

I think i will have to write the cellphonedb counts file and ensure the gene names don't become column one and rerun the cellphonedb? Would you agree? 

thanks 
Rachel

**Comment by rachel662** [comment]
Hi, I attach a few screenshots
I solved the issue of the NA appearing in the first column, I thought this was why it couldn't find any genes in the expression matrix, however I still get the same error upon fixing this?

<img width="193" alt="Screenshot 2021-02-20 at 21 44 44" src="https://user-images.githubusercontent.com/63318678/108609307-fe2bce00-73c4-11eb-95f3-b787cbe93ded.png">
<img width="862" alt="Screenshot 2021-02-20 at 21 45 19" src="https://user-images.githubusercontent.com/63318678/108609308-ff5cfb00-73c4-11eb-8fb6-cbbba8c5ba4c.png">

Thanks so much for your help
Rachel

**Comment by zktuong** [comment]
Hi Rachel, I think the issue with geneDotPlot is that you are trying to plot CXCL13, LTB, LTBR, which are gene symbols whereas your seurat object contains ENSG ensembl IDs. The error with pct/cellNumbers is related as it's rrying to count the number of cells expressing the gene but here it's not finding the gene because of the ID mismatch. So perhaps you can try it on a different object where the IDs are correct.

**Comment by zktuong** [comment]
For the issue with the `plot_cpdb`, i think the issus is with how the input files for cpdb are generated. Basically the number rownames shouldn't be there. This is how i make the files:

```R
# write the meta file
write.table(data.frame(Cell = row.names(dat@meta.data), cell_type = dat$cpdb_celltype), "meta.txt", quote = FALSE, sep = "\t", row.names = FALSE)

# write expression matrix
library(biomaRt)
mart <- useMart("ensembl", dataset="hsapiens_gene_ensembl")
m <- getBM(attributes=c("external_gene_name","ensembl_gene_id", "mmusculus_homolog_associated_gene_name"), mart=mart)

counts <- GetAssayData(object = dat)
idx <- match(row.names(counts), m$mmusculus_homolog_associated_gene_name)
ids <- m$ensembl_gene_id[idx]

counts <- counts[-which(is.na(ids)), ]
ids <- ids[!is.na(ids)]

counts2 <- data.frame(Gene = ids, counts, check.names = FALSE)

write.table(counts2, "exp_mat.txt", quote = FALSE, sep = "\t", row.names = FALSE)
```

Alternatively, you can try and convert your seurat object with normalized expression data into a `.h5ad` object and use the cellphonedb currently at https://github.com/zktuong/cellphonedb which accepts a `.h5ad` input:
```R
library(reticulate)
ad <- import('anndata') # only works if anndata is installed on your current python path for example through `pip install anndata`

df <- as.matrix(Seurat::GetAssayData(dat))
gene_symbol <- h2m$external_gene_name[match(row.names(df), h2m$ensembl_gene_id)]
adata <- ad$AnnData(Matrix::t(Matrix::Matrix(df, sparse = T)), # convert the expression matrix to sparse and transpose it
	obs = dat@meta.data, # original metadata if you want, not important
	var = data.frame(row.names = row.names(df), gene = gene_symbol)) # dataframe containing names of gene symbols
adata$write('adata.h5ad')
```
and then you run cellphonedb with
```bash
cellphonedb method statistical_analysis meta.txt adata.h5ad --output-path=out ...
```

Let me know if this works?

**Comment by rachel662** [comment]
hi there
thanks for this! will I have to create a new seurat object with the counts and meta data input files for cellphonedb again like last time? or should I just used the original one I used to write the counts and metadata input files from?

**Comment by zktuong** [comment]
You can use what you originally had, but for geneDotPlot to work, the symbols would have to match up.

**Comment by rachel662** [comment]
Hi there, 

thanks so much for your help, I really appreciate it - running the cellphonedb worked great again 

geneDotPlot now works, but for some reason it still says 
`Removed 21 rows containing missing values (geom_point).`

plot_cdbp - which was working before, now gives the error 
` Cannot find cell types. The error is mismatch between cell_type2 and the cpdb metadata`

I don't quite understand why this is happening, as the column in my metadata from the original object with all the cell identities is called cell_type and that's what I put for the idents argument?
Is this to do with the loss of genes during the conversion from mouse gene names to human ensembl gene names?

Again thanks so much, sorry for all my questions 
Rachel

**Comment by zktuong** [comment]
What's the full command you are using for `plot_cpdb`?

**Comment by rachel662** [comment]
plot_cpdb(cell_type1 = 'TRC', cell_type2 = 'LTi-Like ILC3', scdata = merged_object,
	idents = "cell_type", # column name where the cell ids are located in the metadata 
	means = means2, pvals = pvalues2,
	genes = c("Ltb", "Ltbr", "Kitl", "Kit", "Ccr6")) + 
small_axis(fontsize = 5) + small_grid() + small_guide() + small_legend(

**Comment by zktuong** [comment]
does it work if your genes are capitalized?

**Comment by zktuong** [comment]
and also can you print what's `unique(merge_object$cell_type)`?

**Comment by rachel662** [comment]
Hi there, 
unfortunately it doesn't work if the genes are capitalised, 
`unique(merged_object$cell_type)
 [1] Cxcl9+ TRC    Nr4a1+ SC     TRC           Ccl19lo TRC   PvC           MRC           Inmt+ SC      CD34+ SC     
 [9] FDC           NCR+ ILC3     Unknown       ex-ILC3/ILC1  ILC2          LTi-Like ILC3
14 Levels: Ccl19lo TRC CD34+ SC Cxcl9+ TRC ex-ILC3/ILC1 FDC ILC2 Inmt+ SC LTi-Like ILC3 MRC NCR+ ILC3 Nr4a1+ SC ... Unknown`

**Comment by zktuong** [comment]
ok. how about unique cpdb metadata cell_type column?

The issue is it cannot find `LTi-Like ILC3` in either the seurat object and/or the the meta file. Can you confirm that they are in both objects/files?

**Comment by rachel662** [comment]
Hi there
I checked in both and it is there

`unique(meta$cell_type)
 [1] "Cxcl9+ TRC"    "Nr4a1+ SC"     "TRC"           "Ccl19lo TRC"   "PvC"           "MRC"           "Inmt+ SC"     
 [8] "CD34+ SC"      "FDC"           "NCR+ ILC3"     "Unknown"       "ex-ILC3/ILC1"  "ILC2"          "LTi-Like ILC3"
> `

if i try creating a new seurat object with the cellphonedb input counts and metdata files I get this error when running plot_cbdp
`Error in c_type1[[i]] : subscript out of bounds`

thanks so much for all your help

**Comment by zktuong** [comment]
Hmm sorry but can you try and recreate your cellphonedb input and seurat object, this time removing all special characters, +, - , / spaces etc. It might be the issue and i'll have to work out where is going wrong.

**Comment by rachel662** [comment]
Hi
Sure, I can try that - do you mean the special characters and spaces in the cell types?
Weirdly, when I create a Seurat object from the counts and metadata file I ran in cellphonedb the first time plot_cpdb works, but genDotplot doesn't 

thanks so much again for your time, I really appreciate it

**Comment by zktuong** [comment]
> Hi
> Sure, I can try that - do you mean the special characters and spaces in the cell types?
> Weirdly, when I create a Seurat object from the counts and metadata file I ran in cellphonedb the first time plot_cpdb works, but genDotplot doesn't
> 
> thanks so much again for your time, I really appreciate it

yes, in the cell types.

**Comment by zktuong** [comment]
Hi Rachel, I have found the problem. It's because of the '-' in LTi-like ILC3 that's causing the issue. I hope to push out a fix in a about an hour.

**Comment by zktuong** [comment]
@rachel662 I believe this issue is now fixed. please try and install v1.1.8. and see if it works.

Cheers

**Comment by rachel662** [comment]
Hi there

I've tried running my code again and unfortunately the error is still occurring, Genedotplot still works but plot_cpdb
when I import the counts and metadata file I used for cellphonedb into R, there is a mismatch in the number of cells (6678 in the counts and 6677 in the metadata) i'm wondering if this could be the cause of the issue? 

thanks so much 
Rachel

**Comment by rachel662** [comment]
Just one other thing, 
I'm trying to convert to a h5ad object, and I'm just wondering where you get the h2m from in the code below?
I don't have a h2m object defined - other than that I have anndata installed successfully 

`library(reticulate)
ad <- import('anndata') # only works if anndata is installed on your current python path for example through `pip install anndata`

df <- as.matrix(Seurat::GetAssayData(dat))
gene_symbol <- h2m$external_gene_name[match(row.names(df), h2m$ensembl_gene_id)]
adata <- ad$AnnData(Matrix::t(Matrix::Matrix(df, sparse = T)), # convert the expression matrix to sparse and transpose it
	obs = dat@meta.data, # original metadata if you want, not important
	var = data.frame(row.names = row.names(df), gene = gene_symbol)) # dataframe containing names of gene symbols
adata$write('adata.h5ad')`

Again, thanks so much for your help and sorry to bother you with all these questions
Cheers
Rachel

**Comment by zktuong** [comment]
That's ok.

h2m is from:

```R
library(biomaRt)
mart <- useMart("ensembl", dataset="hsapiens_gene_ensembl")
h2m <- getBM(attributes=c("external_gene_name","ensembl_gene_id"), mart=mart)
```

I used the code below to test whether the naming structure now works:
```R
# load example data set
library(ktplots)
data(kidneyimmune)
data(cpdb_output)

# edit the example objects to simulate Rachel's objects
# rename B cells to TRC
kidneyimmune$celltype <- gsub('B cell', 'TRC', kidneyimmune$celltype)
colnames(means) <- gsub('B cell', 'TRC', colnames(means))
colnames(pvals) <- gsub('B cell', 'TRC', colnames(pvals))

# rename NK cells to LTi-Like ILC3
kidneyimmune$celltype <- gsub('NK cell', 'LTi-Like ILC3', kidneyimmune$celltype)
colnames(means) <- gsub('NK cell', 'LTi-Like ILC3', colnames(means))
colnames(pvals) <- gsub('NK cell', 'LTi-Like ILC3', colnames(pvals))

# remove the original split.by tags
colnames(means) <- gsub('Wilms2_|TxK1_|RCC1_|RCC2_|RCC3_|Wilms3_|TxK4_|VHLRCC_|Wilms1_|Teen_|Tx_|TxK3_|TxK2_|PapRCC', '', colnames(means))
colnames(pvals) <- gsub('Wilms2_|TxK1_|RCC1_|RCC2_|RCC3_|Wilms3_|TxK4_|VHLRCC_|Wilms1_|Teen_|Tx_|TxK3_|TxK2_|PapRCC', '', colnames(pvals))

# transpose and average to get rid of duplicate columns
means_df <- as.data.frame(t(means[,c(12:ncol(means))]))
pvals_df <- as.data.frame(t(pvals[,c(12:ncol(pvals))]))
means_df$dup <- gsub('[.].*', '', row.names(means_df))
pvals_df$dup <- gsub('[.].*', '', row.names(pvals_df))
means_df <- split(means_df, means_df$dup)
pvals_df <- split(pvals_df, pvals_df$dup)
means_df <- t(do.call(rbind, lapply(means_df, function(x) { colMeans(x[1:ncol(x)-1])})))
pvals_df <- t(do.call(rbind, lapply(pvals_df, function(x) { colMeans(x[1:ncol(x)-1])})))

# concatenate with original first 11 columns
newmeans <- cbind(means[,1:11], means_df)
newpvals <- cbind(pvals[,1:11], pvals_df)

# plot_cpdb
plot_cpdb(cell_type1 = 'TRC', cell_type2 = 'LTi-Like ILC3', scdata = kidneyimmune,
	idents = "celltype", # column name where the cell ids are located in the metadata
	means = newmeans, pvals = newpvals,
	genes = c("LTB", "LTBR", "KITL", "KIT", "CCR6"))
```
and it generates the following plot:
![image](https://user-images.githubusercontent.com/26215587/108637568-30036a00-7483-11eb-9d4d-fdf777a6f7e8.png)
![image](https://user-images.githubusercontent.com/26215587/108637545-0fd3ab00-7483-11eb-90b2-9dea30016b2f.png)

if i remove `LTB` and `LTBR` from the code, i.e.:
```R
plot_cpdb(cell_type1 = 'TRC', cell_type2 = 'LTi-Like ILC3', scdata = kidneyimmune,
	idents = "celltype", # column name where the cell ids are located in the metadata
	means = newmeans, pvals = newpvals,
	genes = c("KITL", "KIT", "CCR6"))
```
then I get the following error:
![image](https://user-images.githubusercontent.com/26215587/108637630-604b0880-7483-11eb-9494-d6764e5001da.png)
And this just means that `KITL`, `KIT` and `CCR6` are not found in the cellphonedb results. Is this what you are seeing?

**Comment by rachel662** [comment]
Hi there
for some reason now, whether I use a new seurat object created from the input metadata and counts files (both ones from my first try and written with your code today) or with the original seurat object I wrote them from I still get the error 

`Error in plot_cpdb(cell_type1 = "TRC", cell_type2 = "LTi-Like ILC3", scdata = merged_object, : Cannot find cell types. The error is mismatch between cell_type2 and the cpdb metadata.`

when using plot_cpdb
genedotplot is working fine with the original seurat object so thanks you for that!

when trying to run adata$write("adata.h5ad") I get the error:
Error: attempt to apply non-function
Do you also know why this is?

thanks so much 
Rachel

**Comment by zktuong** [comment]
@rachel662, can you send me the 3 files (seurat RDS, means, pvals) to me kt16@sanger.ac.uk and i can take a closer look? If thr RDS file is too big, just subset to only TRC and LTi-Like ILC3 clusters.

**Comment by zktuong** [comment]
@rachel662 I worked our that the issue was with the special characters like `+`, and i pushed a fix yesterday that seems to have corrected it. Can you try re-installing and see if this works now for you?

**Comment by rachel662** [comment]
Hi Kelvin
I’m so sorry it’s taken me so long to get to back to you, I had to pause on coding for a while in the end due to other things, I have just given this a try and unfortunately I still get the same error, I have the column with my cell types currently as a type “factor”,  I wondered if the fact that it’s not a vector might be the problem?

**Comment by zktuong** [comment]
That should be fine. Can you send me the objects to kt16@sanger.ac.uk and i will take a closer look?

**Comment by zktuong** [comment]
Hi @rachel662, i think i've finalled managed to solve this. Sorry for the delay. Can you try with version 1.1.12 and see if it works now?

The issue is as above:
> @rachel662 I worked out that perhaps the issue was with the special characters like `+`, and i pushed a fix yesterday that seems to have corrected it. Can you try re-installing and see if this works now for you?

but it seems that there were several spots that i missed. I've went through with this some help and i think/hope it works for you now.

**Comment by rachel662** [comment]
Hi there, 
thanks so much for still coming back to this, I really appreciate it, I have tried this and it now works if I use the means and pvalues file that I created originally - however does you code allow for '/' ? As for cell-types with the forward slash in the name the code doesn't work

Interestingly, with the means and pvalues file I generated using the code you use above to generate the cpdb input files, I still get the same issue entirely - so not entirely sure what is going on here, the only thing I can see is that my means and pvalues files, the names of the interacting cell types  I generated using your code are separated by dots, whereas in the input files I generated myself they are separated by the ' I ' operator?  So I don't know if the interacting cell types being separated by dots is causing the issue? 

i.e.  cell..type1.cell..type2  versus Cell type1 | Cell type2

so I basically was just wondering if I've done something else wrong there? would you expect dots to be separating the interacting cell types and spaces within the names? or should it be the | operator? 

thanks so much again

**Comment by zktuong** [comment]
hmm i hardcoded a grep pattern:
```
pattern <- "/|:|\\?|\\|\\\\|\\*|\\+"
ct1 <- grep(pattern, cell_type1)
```
I think this should deal with `+`, `*`, `/`, `|`, `?`, and `:`. 
I think '\' doesn't work and probably requires a better pattern to catch it.
No idea what happened with `cell..type1.cell..type2 versus Cell type1 | Cell type2` but i'm guessing the spaces got turned into `.` when you are reading in R? Maybe use `check.names = FALSE` when reading.

Anyway, my advice is not not use any special characters or spaces when possible in general - just use underscores and words and this will have the least issues.

**Comment by zktuong** [comment]
Ok i've updated the search pattern and it should now work with backslash `\` properly in version `1.1.13`.
Regarding `cell..type1.cell..type2 versus Cell type1 | Cell type2`, `read.delim(..., check.names = FALSE)` should solve that.

**Comment by rachel662** [comment]
Hi there, 
thanks so much for this! I really appreciate your help and have learnt a lot, think my coding skills have improved massively so thanks for taking the time to help me solve these issues

**Comment by zktuong** [comment]
No worries. If there's no further issues on this point, i will close the issue.

Feel free to open a new one if you find something is not working again.

Cheers

**Comment by hemantgujar** [comment]
Hi I am still getting an error. 
Are numbers allowed in cell-types ? 

> plot_cpdb(
   scdata=x,
   cell_type1="8",
   cell_type2=".",  # this means all cell-types
   celltype_key="celltype",
   idents = "seurat_clusters",
   means=means3,
   pvals=pvals3,
   genes=c("PTPRC", "TNFSF13"),
   title="interacting interactions!",
 )

Error in c_type1[[i]] : subscript out of bounds

> levels(x@active.ident)

 [1] "macrophage_5" "macrophage_4" "macrophage_3" "macrophage_2" "macrophage_1" "macrophage_0" "T_Cells_04_1"
 [8] "T_Cells_04_0" "T_Cells_03_1" "T_Cells_03_0" "T_Cells_00_2" "T_Cells_00_1" "T_Cells_00_0" "T_Cells_01_4"
[15] "T_Cells_01_3" "T_Cells_01_2" "T_Cells_01_1" "T_Cells_01_0" "5"            "6"            "7"           
[22] "8"            "9"            "10"           "11"      

I am using seurat object as scdata. 

Can anyone please help. Thanks.
